### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by Acidham** [wx-Yao/alfred-cheat#1]
In the readme.md you point to https://github.com/wx-Yao/alfred-cheat/blob/master as an example for writing a cheat sheet → not found

**Comment by wx-Yao** [comment]
Sorry for that. It's just an anchor to the "Parsing rule" section in the same page. I'll fix it now. :)

**Comment by wx-Yao** [comment]
Close the issue because it's resolved. Reopen it if have any questions.
