### ISSUE TITLE
is it possible to copy result to clipboard?

### ISSUE THREAD

**Issue by underlow** [wx-Yao/alfred-cheat#2]
is it possible to copy result to clipboard or paste directly to iTerm2?

**Comment by wx-Yao** [comment]
Copy to pasteboard is easy to implement. But it might be hard to paste to iTerm2 "directly".

If I'm about to add this feature, it'll be enough just "copy to pasteboard" and `ctrl-v`. What do you think?

**Comment by wx-Yao** [comment]
Hi, the feature has been added. Please refer to the latest [release](https://github.com/wx-Yao/alfred-cheat/releases).

Now you can hit enter to directly copy the command to the frontest application (iTerm2 or any other application that support paste, as you wish), or use cmd+c to copy to clipboard. 

For future users, If you don't expect hitting enter to directly paste, please toggle it off in the workflow setting (uncheck the box). 
![image](https://user-images.githubusercontent.com/20643897/60901578-8d987200-a2b1-11e9-8943-3a8fb78b98aa.png)

**Comment by wx-Yao** [comment]
close as the issue is resolved.

**Comment by underlow** [comment]
Great,  thank you
