### ISSUE TITLE
Search does not work if a dictionary exists

### ISSUE THREAD

**Issue by Blackvz** [wx-Yao/alfred-cheat#6]
If you have a dictionary in your .cheats/ folder, the "--search" option will stop working.

![image](https://user-images.githubusercontent.com/12122294/62166404-f7d88b80-b320-11e9-9ca8-8ebf4c5bcc29.png)

**Comment by wx-Yao** [comment]
Oh that's expected cuz I assume no directory at the beginning. Thanks bro. Will fix in the next release.

**Comment by wx-Yao** [comment]
Bug fixed. Check for the new release. Thanks for the report and pls reopen the issue if it still doesn't work.
