### ISSUE TITLE
Not compatible with Alfred 3

### ISSUE THREAD

**Issue by RoshanPAN** [wx-Yao/alfred-cheat#8]
![image](https://user-images.githubusercontent.com/17009565/62515080-17b2f800-b7d6-11e9-922d-25b920a9a8b9.png)

**Comment by wx-Yao** [comment]
Sorry to hear that. But with little information, I don't know what I can do. I suggest you upgrade to Alfred 4. Feel free to reopen it if you have any suggestions.
